Java'2. Exceptions
OdaryMe/java-core2-july-29 pull request #2
Opened 2024-08-02 06:36 UTC by OdaryMe

2024-08-02 12:13 UTC, DarkSavant7 approved these changes

2024-08-02 12:13 UTC, dark-savant-of-guardia commented on src/main/java/ru/geekbrains/java_core2/lessons/l2_exceptions/MyArrayDataException.java
> +public class MyArrayDataException extends NumberFormatException {
хорошее решение унаследовать от более общих исключений. Я только обращу внимание, что оно должно не изменять тогда родительское, а уточнять его. Конкретно в этой ситуации хорошою

2024-08-02 12:13 UTC, DarkSavant7 commented on src/main/java/ru/geekbrains/java_core2/lessons/l2_exceptions/Homework9.java
> +                if (arr.length != 4 || arr[i].length != 4) {
ну вот тут тоже вроде и корректно, но по идее проверку на arr.length != 4 стоит сделать на 2 уровня выше, вне циклов, потому что зачем проверять его сто раз? ты еще тут проверяешь на каждую ячейку, ну вообще.
А проверку arr[i].length != 4 на один уровень выше, чтобы тоже не проверять много раз на каждой ячейке. 

```Java
...
if (arr.length != 4) {
throw new MyArraySizeException("Wrong Array Size");
}

 for (int i = 0; i < arr.length; i++) {
if (arr.length[i] != 4) {
throw new MyArraySizeException("Wrong Array Size");
}
... тут далее твой код с парсингом и другими исключениями.

2024-08-02 12:13 UTC, DarkSavant7 commented on src/main/java/ru/geekbrains/java_core2/lessons/l2_exceptions/Homework9.java
> +        int[][] set = new int[4][4];
И вот это вот 4 волшебное число, лучше не использовать. Можно вынести в константу. Или брать из конфига или аргументов (вынеси в константу)

2024-08-02 12:13 UTC, DarkSavant7 commented on src/main/java/ru/geekbrains/java_core2/lessons/l2_exceptions/Homework9.java
> +    public static void parseString (String[][] arr) {
Что за имя метода? Ты ж не строку парсишь. А парсишь двумерный массив из кучи строк и преобразуешь их в целые числа и складываешь. Название вводит в заблуждение.

2024-08-02 12:13 UTC, DarkSavant7 commented on src/main/java/ru/geekbrains/java_core2/lessons/l2_exceptions/Homework9.java
> +                    String message = "Invalid cell " + i + ":" + j;
Это отличное решение переписывать не надо, просто для информации, есть в String статический метод format, можно еще и так:
```Java
var message = String.format("Invalid cell %d:%d%n", i, j);
```
Ну то есть твой printf это комбинация OutputStream::print + String::format
Ну и с использованием StringBuilder тоже кстати, но он тут точно нафиг не нужен.

2024-08-02 12:13 UTC, DarkSavant7 commented on src/main/java/ru/geekbrains/java_core2/lessons/l2_exceptions/Homework9.java
> +        }
тоже не вполне то, что надо было.
Если ты запускаешь разные варианты ошибок в одном блоке, то выполнится только первый, будет выброшено исключение, остальные будут проигнорированы.
Я не говорю, что так надо делать в разработке, но конкретно здесь если ты хочешь поймать КАЖДУЮ ошибку, то надо ловить в отдельных блоках.

2024-08-02 12:13 UTC, DarkSavant7 commented on src/main/java/ru/geekbrains/java_core2/lessons/l2_exceptions/Homework9.java
> +public class Homework9 {
Классы предлагаю тоже начинать называть чуть более осмысленно.

2024-08-02 12:22 UTC, OdaryMe commented on src/main/java/ru/geekbrains/java_core2/lessons/l2_exceptions/MyArrayDataException.java
> +public class MyArrayDataException extends NumberFormatException {
Здесь не очень понимаю. А я изменила родительское? Вроде нет.

2024-08-02 14:04 UTC, DarkSavant7 approved these changes

2024-08-02 14:04 UTC, DarkSavant7 commented on src/main/java/ru/geekbrains/java_core2/lessons/l2_exceptions/Homework9.java
> +        int[][] set = new int[ARRSIZE][ARRSIZE];
Я может у первый раз не заметил, но что это и зачем?

2024-08-03 06:47 UTC, DarkSavant7 requested changes

2024-08-03 06:47 UTC, DarkSavant7 commented on src/main/java/ru/geekbrains/java_core2/lessons/l2_exceptions/Experience.java
> +                if (charArr[j] != '0' || charArr[j] != '1' || charArr[j] != '2' || charArr[j] != '3' ||
Тут должно быть И как я вижу, твоя логика не должна работать. То есть &&

2024-08-03 06:47 UTC, DarkSavant7 commented on src/main/java/ru/geekbrains/java_core2/lessons/l2_exceptions/Experience.java
> +            String s = Arrays.toString(myArr[i]);
Зачем? Там же запятые, скобки и  тд

2024-08-05 04:29 UTC, merged